#khoinda:
#  bot:
#    username: pat_cmc_bot
#    token: 6670723908:AAEuURQNvDnysYsxfHLxWYzVA8I7ujwMIXA
#    bot-route-packages:
#      - com.example.demo

logging:
  level:
    org:
      apache:
        http: INFO
      telegram: ERROR

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/telegrambot?useUnicode=yes&characterEncoding=UTF-8
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: '587'
    username: tuanpa.tpa@gmail.com
    password: uclvfgwowkkkmlir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
author:
  name: PAT
  email: tuanpa.tpa@gmail.com
template:
  email: classpath:/templates